extends: default
rules:
  line-length: disable
  document-start: disable
  truthy: disable
  comments: disable
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  indentation:
    spaces: consistent
    indent-sequences: whatever
