export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "qa",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "all",
        "ci",
        "clean",
        "config",
        "deps",
        "docs",
        "release",
        "repo",
        "recon",
        "script",
        "scripts",
        "test",
        "tests",
        "tools",
      ],
    ],
    "scope-empty": [0],
    "subject-empty": [2, "never"],
    "type-empty": [2, "never"],
    "header-max-length": [2, "always", 100],
    "subject-case": [0],
  },
};
